## Numpy array and basics
learn about numpy with chai aur code

import numpy as np

## creating array from list

In [5]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4])
print("1D array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)


1D array: [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [ ]:
py_list =[1,2,3]
print("python list multiplication",py_list * 2)  #[1,2,3,1,2,3]


np_array =np.array([1,2,3])            ##aliment by multiplication
print("python array multiplication",np_array *2)  #[2 4 6]



import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List opraction time:",time.time()-start)


start = time.time()
np_array = np.arange(1000000) *2
print("\n Numpy opraction time:",time.time() -start)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 List opraction time: 0.058934688568115234

 Numpy opraction time: 0.003215789794921875


### creating array from scratch

In [22]:
zeros =np.zeros((3,4))
print("zero array: \n",zeros)

ones=np.ones((4,5))
print("ones array:\n",ones)

full=np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array:\n",random)


sequnce = np.arange(0, 11,2 )
print("sequnce array:\n",sequnce)

zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array:
 [[0.08059576 0.16521942 0.14274892]
 [0.39226977 0.24007759 0.7807361 ]]
sequnce array:
 [ 0  2  4  6  8 10]


###   Vector ,Matrix and Tensor

In [11]:

vector = np.array([1,2,3])  
print("vector:\n",vector)


matrix = np.array([[1,2,3],[4,5,6]])
print("matrix:",matrix)


tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print("tensor:",tensor)

vector:
 [1 2 3]
matrix: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### Array propertise

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print("shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)           #bite

shape (2, 3)
Dimension 2
size 6
Dtype int64


### Array Resheping

In [ ]:
arr = np.arange(12)
print("originalm array",arr)

reshaped = arr.reshape((3,4))                # 3*4 matrix
print("\n Reshaped array",reshaped)

flattened = reshaped.flatten()               # copy value return
print("\n Flattened array",flattened)

raveled = reshaped.ravel()                  # original value  return ravel
print("\n rabeled array",raveled)

# Transpose
transpose = reshaped.T                           # Transpose
print("\n Transpose attay",transpose)

originalm array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 rabeled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose attay [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
