### Numpy array oprections

In [2]:
import numpy as np

In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing",arr[2:7])
print("with step",arr[1:8:2])
print("Negative indexing",arr[-3])

Basic slicing [3 4 5 6 7]
with step [2 4 6 8]
Negative indexing 8


In [24]:
arr_2d=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print("specific element",arr_2d[1,2])            #1=row one.2=culomb two
print("Entire row",arr_2d[1])
print("Entire row",arr_2d[:,1])

specific element 6
Entire row [4 5 6]
Entire row [2 5 8]


In [4]:
import numpy as np

### Sorting

In [ ]:
unsorted =np.array([9,7,5,3,1,2,4,6,8])
print("Sorted array",np.sort(unsorted))

arr_2D_unsorted=np.array([[3,1],
                          [1,2],
                          [2,3]])
print("Sorting 2D array by column",np.sort(arr_2D_unsorted,axis=0))

Sorted array [1 2 3 4 5 6 7 8 9]
Sorting 2D array by column [[1 1]
 [2 2]
 [3 3]]


### Filter

In [19]:
number=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=number[number % 2 ==0]
print("Even numbers",even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [21]:
mask=number>5
print("Number greater than 5",number[mask])

Number greater than 5 [ 6  7  8  9 10]


### Fancy indexing VS np.where()

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

indices=[0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("NP where",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [11]:

condition_array=np.where(numbers>5,"true" ,"false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


###     ADDING AND REMOVING DATA

In [12]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


##array compatibility

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([8,9,2])

print("compatibility shapes",a.shape == b.shape)

compatibility shapes False


##add row and columb

In [ ]:
original=np.array([[1,2],[3,4]])

new_row=np.array([5,6])
with_new_row=np.vstack((original,new_row))
print(original)
print("with new row",with_new_row)



new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("with new col",with_new_col)


[[1 2]
 [3 4]]
with new row [[1 2]
 [3 4]
 [5 6]]
with new col [[1 2 7]
 [3 4 8]]


##removing

In [22]:
arr=np.array([1,2,3,4,5])
delete=np.delete(arr,2)
print(delete)


[1 2 4 5]
